version: 2
archives:
  - id: archive
    name_template: '{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}'
builds:
  - env:
      - CGO_ENABLED=0
    binary: pulumi-resource-splight
    dir: provider
    goarch:
      - amd64
      - arm64
    goos:
      - darwin
      - windows
      - linux
    ldflags:
      - -X github.com/splightplatform/pulumi-splight/provider/pkg/version.Version={{ .Version }}
    main: ./cmd/pulumi-resource-splight
changelog:
  disable: true
release:
  disable: false
  prerelease: auto
