// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Splight.Splight
{
    /// <summary>
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using System.Text.Json;
    /// using Pulumi;
    /// using Splight = Splight.Splight;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var functionTest = new Splight.Function("functionTest", new()
    ///     {
    ///         Description = "Created with Terraform",
    ///         Type = "rate",
    ///         TimeWindow = 600,
    ///         RateValue = 10,
    ///         RateUnit = "minute",
    ///         TargetVariable = "A",
    ///         TargetAsset = 
    ///         {
    ///             { "id", "49551a15-d79b-40dc-9434-1b33d6b2fcb2" },
    ///             { "name", "An asset" },
    ///         },
    ///         TargetAttribute = 
    ///         {
    ///             { "id", "49551a15-d79b-40dc-9434-1b33d6b2fcb2" },
    ///             { "name", "An attribute" },
    ///         },
    ///         FunctionItems = new[]
    ///         {
    ///             new Splight.Inputs.FunctionFunctionItemArgs
    ///             {
    ///                 RefId = "A",
    ///                 Type = "QUERY",
    ///                 ExpressionPlain = "",
    ///                 QueryPlain = JsonSerializer.Serialize(new[]
    ///                 {
    ///                     new Dictionary&lt;string, object?&gt;
    ///                     {
    ///                         ["$match"] = new Dictionary&lt;string, object?&gt;
    ///                         {
    ///                             ["asset"] = "49551a15-d79b-40dc-9434-1b33d6b2fcb2",
    ///                             ["attribute"] = "c1d0d94b-5feb-4ebb-a527-0b0a34196252",
    ///                         },
    ///                     },
    ///                 }),
    ///             },
    ///             new Splight.Inputs.FunctionFunctionItemArgs
    ///             {
    ///                 RefId = "B",
    ///                 Type = "QUERY",
    ///                 ExpressionPlain = "",
    ///                 QueryPlain = JsonSerializer.Serialize(new[]
    ///                 {
    ///                     new Dictionary&lt;string, object?&gt;
    ///                     {
    ///                         ["$match"] = new Dictionary&lt;string, object?&gt;
    ///                         {
    ///                             ["asset"] = "49551a15-d79b-40dc-9434-1b33d6b2fcb2",
    ///                             ["attribute"] = "c1d0d94b-5feb-4ebb-a527-0b0a34196252",
    ///                         },
    ///                     },
    ///                 }),
    ///             },
    ///         },
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// ```sh
    /// $ pulumi import splight:index/function:Function [options] splight_function.&lt;name&gt; &lt;function_id&gt;
    /// ```
    /// </summary>
    [SplightResourceType("splight:index/function:Function")]
    public partial class Function : global::Pulumi.CustomResource
    {
        /// <summary>
        /// schedule value for cron
        /// </summary>
        [Output("cronDom")]
        public Output<int> CronDom { get; private set; } = null!;

        /// <summary>
        /// schedule value for cron
        /// </summary>
        [Output("cronDow")]
        public Output<int> CronDow { get; private set; } = null!;

        /// <summary>
        /// schedule value for cron
        /// </summary>
        [Output("cronHours")]
        public Output<int> CronHours { get; private set; } = null!;

        /// <summary>
        /// schedule value for cron
        /// </summary>
        [Output("cronMinutes")]
        public Output<int> CronMinutes { get; private set; } = null!;

        /// <summary>
        /// schedule value for cron
        /// </summary>
        [Output("cronMonth")]
        public Output<int> CronMonth { get; private set; } = null!;

        /// <summary>
        /// schedule value for cron
        /// </summary>
        [Output("cronYear")]
        public Output<int> CronYear { get; private set; } = null!;

        /// <summary>
        /// The description of the resource
        /// </summary>
        [Output("description")]
        public Output<string> Description { get; private set; } = null!;

        /// <summary>
        /// traces to be used to compute the results
        /// </summary>
        [Output("functionItems")]
        public Output<ImmutableArray<Outputs.FunctionFunctionItem>> FunctionItems { get; private set; } = null!;

        /// <summary>
        /// The name of the resource
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// [day|hour|minute] schedule unit
        /// </summary>
        [Output("rateUnit")]
        public Output<string> RateUnit { get; private set; } = null!;

        /// <summary>
        /// schedule value
        /// </summary>
        [Output("rateValue")]
        public Output<int> RateValue { get; private set; } = null!;

        /// <summary>
        /// asset where to ingest results
        /// </summary>
        [Output("targetAsset")]
        public Output<ImmutableDictionary<string, string>> TargetAsset { get; private set; } = null!;

        /// <summary>
        /// attribute where to ingest results
        /// </summary>
        [Output("targetAttribute")]
        public Output<ImmutableDictionary<string, string>> TargetAttribute { get; private set; } = null!;

        /// <summary>
        /// variable to be considered to be ingested
        /// </summary>
        [Output("targetVariable")]
        public Output<string> TargetVariable { get; private set; } = null!;

        /// <summary>
        /// window to fetch data from. Data out of that window will not be considered for evaluation
        /// </summary>
        [Output("timeWindow")]
        public Output<int> TimeWindow { get; private set; } = null!;

        /// <summary>
        /// [cron|rate] type for the cron
        /// </summary>
        [Output("type")]
        public Output<string> Type { get; private set; } = null!;


        /// <summary>
        /// Create a Function resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Function(string name, FunctionArgs args, CustomResourceOptions? options = null)
            : base("splight:index/function:Function", name, args ?? new FunctionArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Function(string name, Input<string> id, FunctionState? state = null, CustomResourceOptions? options = null)
            : base("splight:index/function:Function", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Function resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Function Get(string name, Input<string> id, FunctionState? state = null, CustomResourceOptions? options = null)
        {
            return new Function(name, id, state, options);
        }
    }

    public sealed class FunctionArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// schedule value for cron
        /// </summary>
        [Input("cronDom")]
        public Input<int>? CronDom { get; set; }

        /// <summary>
        /// schedule value for cron
        /// </summary>
        [Input("cronDow")]
        public Input<int>? CronDow { get; set; }

        /// <summary>
        /// schedule value for cron
        /// </summary>
        [Input("cronHours")]
        public Input<int>? CronHours { get; set; }

        /// <summary>
        /// schedule value for cron
        /// </summary>
        [Input("cronMinutes")]
        public Input<int>? CronMinutes { get; set; }

        /// <summary>
        /// schedule value for cron
        /// </summary>
        [Input("cronMonth")]
        public Input<int>? CronMonth { get; set; }

        /// <summary>
        /// schedule value for cron
        /// </summary>
        [Input("cronYear")]
        public Input<int>? CronYear { get; set; }

        /// <summary>
        /// The description of the resource
        /// </summary>
        [Input("description", required: true)]
        public Input<string> Description { get; set; } = null!;

        [Input("functionItems", required: true)]
        private InputList<Inputs.FunctionFunctionItemArgs>? _functionItems;

        /// <summary>
        /// traces to be used to compute the results
        /// </summary>
        public InputList<Inputs.FunctionFunctionItemArgs> FunctionItems
        {
            get => _functionItems ?? (_functionItems = new InputList<Inputs.FunctionFunctionItemArgs>());
            set => _functionItems = value;
        }

        /// <summary>
        /// The name of the resource
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// [day|hour|minute] schedule unit
        /// </summary>
        [Input("rateUnit")]
        public Input<string>? RateUnit { get; set; }

        /// <summary>
        /// schedule value
        /// </summary>
        [Input("rateValue")]
        public Input<int>? RateValue { get; set; }

        [Input("targetAsset", required: true)]
        private InputMap<string>? _targetAsset;

        /// <summary>
        /// asset where to ingest results
        /// </summary>
        public InputMap<string> TargetAsset
        {
            get => _targetAsset ?? (_targetAsset = new InputMap<string>());
            set => _targetAsset = value;
        }

        [Input("targetAttribute", required: true)]
        private InputMap<string>? _targetAttribute;

        /// <summary>
        /// attribute where to ingest results
        /// </summary>
        public InputMap<string> TargetAttribute
        {
            get => _targetAttribute ?? (_targetAttribute = new InputMap<string>());
            set => _targetAttribute = value;
        }

        /// <summary>
        /// variable to be considered to be ingested
        /// </summary>
        [Input("targetVariable", required: true)]
        public Input<string> TargetVariable { get; set; } = null!;

        /// <summary>
        /// window to fetch data from. Data out of that window will not be considered for evaluation
        /// </summary>
        [Input("timeWindow", required: true)]
        public Input<int> TimeWindow { get; set; } = null!;

        /// <summary>
        /// [cron|rate] type for the cron
        /// </summary>
        [Input("type", required: true)]
        public Input<string> Type { get; set; } = null!;

        public FunctionArgs()
        {
        }
        public static new FunctionArgs Empty => new FunctionArgs();
    }

    public sealed class FunctionState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// schedule value for cron
        /// </summary>
        [Input("cronDom")]
        public Input<int>? CronDom { get; set; }

        /// <summary>
        /// schedule value for cron
        /// </summary>
        [Input("cronDow")]
        public Input<int>? CronDow { get; set; }

        /// <summary>
        /// schedule value for cron
        /// </summary>
        [Input("cronHours")]
        public Input<int>? CronHours { get; set; }

        /// <summary>
        /// schedule value for cron
        /// </summary>
        [Input("cronMinutes")]
        public Input<int>? CronMinutes { get; set; }

        /// <summary>
        /// schedule value for cron
        /// </summary>
        [Input("cronMonth")]
        public Input<int>? CronMonth { get; set; }

        /// <summary>
        /// schedule value for cron
        /// </summary>
        [Input("cronYear")]
        public Input<int>? CronYear { get; set; }

        /// <summary>
        /// The description of the resource
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        [Input("functionItems")]
        private InputList<Inputs.FunctionFunctionItemGetArgs>? _functionItems;

        /// <summary>
        /// traces to be used to compute the results
        /// </summary>
        public InputList<Inputs.FunctionFunctionItemGetArgs> FunctionItems
        {
            get => _functionItems ?? (_functionItems = new InputList<Inputs.FunctionFunctionItemGetArgs>());
            set => _functionItems = value;
        }

        /// <summary>
        /// The name of the resource
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// [day|hour|minute] schedule unit
        /// </summary>
        [Input("rateUnit")]
        public Input<string>? RateUnit { get; set; }

        /// <summary>
        /// schedule value
        /// </summary>
        [Input("rateValue")]
        public Input<int>? RateValue { get; set; }

        [Input("targetAsset")]
        private InputMap<string>? _targetAsset;

        /// <summary>
        /// asset where to ingest results
        /// </summary>
        public InputMap<string> TargetAsset
        {
            get => _targetAsset ?? (_targetAsset = new InputMap<string>());
            set => _targetAsset = value;
        }

        [Input("targetAttribute")]
        private InputMap<string>? _targetAttribute;

        /// <summary>
        /// attribute where to ingest results
        /// </summary>
        public InputMap<string> TargetAttribute
        {
            get => _targetAttribute ?? (_targetAttribute = new InputMap<string>());
            set => _targetAttribute = value;
        }

        /// <summary>
        /// variable to be considered to be ingested
        /// </summary>
        [Input("targetVariable")]
        public Input<string>? TargetVariable { get; set; }

        /// <summary>
        /// window to fetch data from. Data out of that window will not be considered for evaluation
        /// </summary>
        [Input("timeWindow")]
        public Input<int>? TimeWindow { get; set; }

        /// <summary>
        /// [cron|rate] type for the cron
        /// </summary>
        [Input("type")]
        public Input<string>? Type { get; set; }

        public FunctionState()
        {
        }
        public static new FunctionState Empty => new FunctionState();
    }
}
