// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Splight.Outputs
{

    [OutputType]
    public sealed class AlertThreshold
    {
        /// <summary>
        /// [alert|warning|no_alert] status value for the threshold
        /// </summary>
        public readonly string Status;
        /// <summary>
        /// optional custom value to be displayed in the platform.
        /// </summary>
        public readonly string? StatusText;
        /// <summary>
        /// value to be considered to compare
        /// </summary>
        public readonly double Value;

        [OutputConstructor]
        private AlertThreshold(
            string status,

            string? statusText,

            double value)
        {
            Status = status;
            StatusText = statusText;
            Value = value;
        }
    }
}
