// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface AlertAlertItem {
    expressionPlain: string;
    queryPlain: string;
    refId: string;
    type: string;
}

export interface AlertThreshold {
    /**
     * [alert|warning|no_alert] status value for the threshold
     */
    status: string;
    /**
     * optional custom value to be displayed in the platform.
     */
    statusText?: string;
    /**
     * value to be considered to compare
     */
    value: number;
}

export interface AssetKind {
    /**
     * kind id
     */
    id: string;
    /**
     * kind name
     */
    name: string;
}

export interface ComponentInput {
    description: string;
    multiple: boolean;
    name: string;
    required: boolean;
    sensitive: boolean;
    type: string;
    value: string;
}

export interface ComponentRoutineConfig {
    description: string;
    multiple: boolean;
    name: string;
    required: boolean;
    sensitive: boolean;
    type: string;
    value: string;
}

export interface ComponentRoutineInput {
    description: string;
    multiple: boolean;
    name: string;
    required: boolean;
    type: string;
    value: outputs.ComponentRoutineInputValue;
    valueType: string;
}

export interface ComponentRoutineInputValue {
    asset: string;
    attribute: string;
}

export interface ComponentRoutineOutput {
    description: string;
    multiple: boolean;
    name: string;
    required: boolean;
    type: string;
    value: outputs.ComponentRoutineOutputValue;
    valueType: string;
}

export interface ComponentRoutineOutputValue {
    asset: string;
    attribute: string;
}

export interface DashboardChartChartItem {
    collection?: string;
    color: string;
    expressionPlain: string;
    hidden?: boolean;
    label?: string;
    /**
     * asset filter
     */
    queryFilterAsset?: outputs.DashboardChartChartItemQueryFilterAsset;
    /**
     * Attribute filter
     */
    queryFilterAttribute?: outputs.DashboardChartChartItemQueryFilterAttribute;
    queryGroupFunction?: string;
    queryGroupUnit?: string;
    queryLimit?: number;
    queryPlain: string;
    querySortDirection?: number;
    refId: string;
    type: string;
}

export interface DashboardChartChartItemQueryFilterAsset {
    /**
     * The ID of this resource.
     */
    id: string;
    name: string;
}

export interface DashboardChartChartItemQueryFilterAttribute {
    /**
     * The ID of this resource.
     */
    id: string;
    name: string;
}

export interface DashboardChartThreshold {
    color: string;
    displayText: string;
    value: number;
}

export interface DashboardChartValueMapping {
    displayText: string;
    matchValue: string;
    order: number;
    type: string;
}

export interface FunctionFunctionItem {
    expressionPlain: string;
    queryPlain: string;
    refId: string;
    type: string;
}

export interface GetAssetKindsKind {
    id: string;
    name: string;
}

