// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Splight.Inputs
{

    public sealed class AlertThresholdArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// [alert|warning|no_alert] status value for the threshold
        /// </summary>
        [Input("status", required: true)]
        public Input<string> Status { get; set; } = null!;

        /// <summary>
        /// optional custom value to be displayed in the platform.
        /// </summary>
        [Input("statusText")]
        public Input<string>? StatusText { get; set; }

        /// <summary>
        /// value to be considered to compare
        /// </summary>
        [Input("value", required: true)]
        public Input<double> Value { get; set; } = null!;

        public AlertThresholdArgs()
        {
        }
        public static new AlertThresholdArgs Empty => new AlertThresholdArgs();
    }
}
