// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as splight from "@splightplatform/pulumi-splight";
 *
 * const myAsset = new splight.Asset("myAsset", {
 *     description: "My Asset Description",
 *     timezone: "America/Los_Angeles",
 *     geometry: JSON.stringify({
 *         type: "GeometryCollection",
 *         geometries: [{
 *             type: "Point",
 *             coordinates: [
 *                 0,
 *                 0,
 *             ],
 *         }],
 *     }),
 * });
 * const myAttribute = new splight.AssetAttribute("myAttribute", {
 *     type: "Number",
 *     unit: "meters",
 *     asset: myAsset.id,
 * });
 * const myAction = new splight.Action("myAction", {
 *     asset: {
 *         id: myAsset.id,
 *         name: myAsset.name,
 *     },
 *     setpoints: [{
 *         value: JSON.stringify(1),
 *         attribute: {
 *             id: myAttribute.id,
 *             name: myAttribute.name,
 *         },
 *     }],
 * });
 * ```
 *
 * ## Import
 *
 * ```sh
 * $ pulumi import splight:index/action:Action [options] splight_action.<name> <action_id>
 * ```
 */
export class Action extends pulumi.CustomResource {
    /**
     * Get an existing Action resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ActionState, opts?: pulumi.CustomResourceOptions): Action {
        return new Action(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'splight:index/action:Action';

    /**
     * Returns true if the given object is an instance of Action.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Action {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Action.__pulumiType;
    }

    /**
     * target asset of the setpoint
     */
    public readonly asset!: pulumi.Output<outputs.ActionAsset>;
    /**
     * the name of the action to be created
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * action setpoints
     */
    public readonly setpoints!: pulumi.Output<outputs.ActionSetpoint[]>;

    /**
     * Create a Action resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ActionArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ActionArgs | ActionState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ActionState | undefined;
            resourceInputs["asset"] = state ? state.asset : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["setpoints"] = state ? state.setpoints : undefined;
        } else {
            const args = argsOrState as ActionArgs | undefined;
            if ((!args || args.asset === undefined) && !opts.urn) {
                throw new Error("Missing required property 'asset'");
            }
            if ((!args || args.setpoints === undefined) && !opts.urn) {
                throw new Error("Missing required property 'setpoints'");
            }
            resourceInputs["asset"] = args ? args.asset : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["setpoints"] = args ? args.setpoints : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Action.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Action resources.
 */
export interface ActionState {
    /**
     * target asset of the setpoint
     */
    asset?: pulumi.Input<inputs.ActionAsset>;
    /**
     * the name of the action to be created
     */
    name?: pulumi.Input<string>;
    /**
     * action setpoints
     */
    setpoints?: pulumi.Input<pulumi.Input<inputs.ActionSetpoint>[]>;
}

/**
 * The set of arguments for constructing a Action resource.
 */
export interface ActionArgs {
    /**
     * target asset of the setpoint
     */
    asset: pulumi.Input<inputs.ActionAsset>;
    /**
     * the name of the action to be created
     */
    name?: pulumi.Input<string>;
    /**
     * action setpoints
     */
    setpoints: pulumi.Input<pulumi.Input<inputs.ActionSetpoint>[]>;
}
