// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * ## Example Usage
 *
 * ## Import
 *
 * ```sh
 * $ pulumi import splight:index/generator:Generator [options] splight_generator.<name> <generator_id>
 * ```
 */
export class Generator extends pulumi.CustomResource {
    /**
     * Get an existing Generator resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: GeneratorState, opts?: pulumi.CustomResourceOptions): Generator {
        return new Generator(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'splight:index/generator:Generator';

    /**
     * Returns true if the given object is an instance of Generator.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Generator {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Generator.__pulumiType;
    }

    /**
     * attribute of the resource
     */
    public /*out*/ readonly activePowers!: pulumi.Output<outputs.GeneratorActivePower[]>;
    /**
     * attribute of the resource
     */
    public /*out*/ readonly dailyEmissionAvoideds!: pulumi.Output<outputs.GeneratorDailyEmissionAvoided[]>;
    /**
     * attribute of the resource
     */
    public /*out*/ readonly dailyEnergies!: pulumi.Output<outputs.GeneratorDailyEnergy[]>;
    /**
     * description of the resource
     */
    public readonly description!: pulumi.Output<string | undefined>;
    /**
     * geo position and shape of the resource
     */
    public readonly geometry!: pulumi.Output<string | undefined>;
    /**
     * kind of the resource
     */
    public /*out*/ readonly kinds!: pulumi.Output<outputs.GeneratorKind[]>;
    /**
     * attribute of the resource
     */
    public /*out*/ readonly monthlyEnergies!: pulumi.Output<outputs.GeneratorMonthlyEnergy[]>;
    /**
     * name of the resource
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * attribute of the resource
     */
    public /*out*/ readonly reactivePowers!: pulumi.Output<outputs.GeneratorReactivePower[]>;
    /**
     * attribute of the resource
     */
    public /*out*/ readonly switchStatuses!: pulumi.Output<outputs.GeneratorSwitchStatus[]>;
    /**
     * tags of the resource
     */
    public readonly tags!: pulumi.Output<outputs.GeneratorTag[] | undefined>;
    /**
     * timezone that overrides location-based timezone of the resource
     */
    public readonly timezone!: pulumi.Output<string>;

    /**
     * Create a Generator resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: GeneratorArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: GeneratorArgs | GeneratorState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as GeneratorState | undefined;
            resourceInputs["activePowers"] = state ? state.activePowers : undefined;
            resourceInputs["dailyEmissionAvoideds"] = state ? state.dailyEmissionAvoideds : undefined;
            resourceInputs["dailyEnergies"] = state ? state.dailyEnergies : undefined;
            resourceInputs["description"] = state ? state.description : undefined;
            resourceInputs["geometry"] = state ? state.geometry : undefined;
            resourceInputs["kinds"] = state ? state.kinds : undefined;
            resourceInputs["monthlyEnergies"] = state ? state.monthlyEnergies : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["reactivePowers"] = state ? state.reactivePowers : undefined;
            resourceInputs["switchStatuses"] = state ? state.switchStatuses : undefined;
            resourceInputs["tags"] = state ? state.tags : undefined;
            resourceInputs["timezone"] = state ? state.timezone : undefined;
        } else {
            const args = argsOrState as GeneratorArgs | undefined;
            resourceInputs["description"] = args ? args.description : undefined;
            resourceInputs["geometry"] = args ? args.geometry : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["tags"] = args ? args.tags : undefined;
            resourceInputs["timezone"] = args ? args.timezone : undefined;
            resourceInputs["activePowers"] = undefined /*out*/;
            resourceInputs["dailyEmissionAvoideds"] = undefined /*out*/;
            resourceInputs["dailyEnergies"] = undefined /*out*/;
            resourceInputs["kinds"] = undefined /*out*/;
            resourceInputs["monthlyEnergies"] = undefined /*out*/;
            resourceInputs["reactivePowers"] = undefined /*out*/;
            resourceInputs["switchStatuses"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Generator.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Generator resources.
 */
export interface GeneratorState {
    /**
     * attribute of the resource
     */
    activePowers?: pulumi.Input<pulumi.Input<inputs.GeneratorActivePower>[]>;
    /**
     * attribute of the resource
     */
    dailyEmissionAvoideds?: pulumi.Input<pulumi.Input<inputs.GeneratorDailyEmissionAvoided>[]>;
    /**
     * attribute of the resource
     */
    dailyEnergies?: pulumi.Input<pulumi.Input<inputs.GeneratorDailyEnergy>[]>;
    /**
     * description of the resource
     */
    description?: pulumi.Input<string>;
    /**
     * geo position and shape of the resource
     */
    geometry?: pulumi.Input<string>;
    /**
     * kind of the resource
     */
    kinds?: pulumi.Input<pulumi.Input<inputs.GeneratorKind>[]>;
    /**
     * attribute of the resource
     */
    monthlyEnergies?: pulumi.Input<pulumi.Input<inputs.GeneratorMonthlyEnergy>[]>;
    /**
     * name of the resource
     */
    name?: pulumi.Input<string>;
    /**
     * attribute of the resource
     */
    reactivePowers?: pulumi.Input<pulumi.Input<inputs.GeneratorReactivePower>[]>;
    /**
     * attribute of the resource
     */
    switchStatuses?: pulumi.Input<pulumi.Input<inputs.GeneratorSwitchStatus>[]>;
    /**
     * tags of the resource
     */
    tags?: pulumi.Input<pulumi.Input<inputs.GeneratorTag>[]>;
    /**
     * timezone that overrides location-based timezone of the resource
     */
    timezone?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Generator resource.
 */
export interface GeneratorArgs {
    /**
     * description of the resource
     */
    description?: pulumi.Input<string>;
    /**
     * geo position and shape of the resource
     */
    geometry?: pulumi.Input<string>;
    /**
     * name of the resource
     */
    name?: pulumi.Input<string>;
    /**
     * tags of the resource
     */
    tags?: pulumi.Input<pulumi.Input<inputs.GeneratorTag>[]>;
    /**
     * timezone that overrides location-based timezone of the resource
     */
    timezone?: pulumi.Input<string>;
}
