// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * ## Example Usage
 *
 * ## Import
 *
 * ```sh
 * $ pulumi import splight:index/segment:Segment [options] splight_segment.<name> <segment_id>
 * ```
 */
export class Segment extends pulumi.CustomResource {
    /**
     * Get an existing Segment resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: SegmentState, opts?: pulumi.CustomResourceOptions): Segment {
        return new Segment(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'splight:index/segment:Segment';

    /**
     * Returns true if the given object is an instance of Segment.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Segment {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Segment.__pulumiType;
    }

    /**
     * attribute of the resource
     */
    public readonly altitude!: pulumi.Output<outputs.SegmentAltitude>;
    /**
     * attribute of the resource
     */
    public readonly azimuth!: pulumi.Output<outputs.SegmentAzimuth>;
    /**
     * attribute of the resource
     */
    public readonly cumulativeDistance!: pulumi.Output<outputs.SegmentCumulativeDistance>;
    /**
     * description of the resource
     */
    public readonly description!: pulumi.Output<string | undefined>;
    /**
     * geo position and shape of the resource
     */
    public readonly geometry!: pulumi.Output<string | undefined>;
    /**
     * kind of the resource
     */
    public /*out*/ readonly kinds!: pulumi.Output<outputs.SegmentKind[]>;
    /**
     * name of the resource
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * tags of the resource
     */
    public readonly tags!: pulumi.Output<outputs.SegmentTag[] | undefined>;
    /**
     * attribute of the resource
     */
    public /*out*/ readonly temperatures!: pulumi.Output<outputs.SegmentTemperature[]>;
    /**
     * attribute of the resource
     */
    public /*out*/ readonly windDirections!: pulumi.Output<outputs.SegmentWindDirection[]>;
    /**
     * attribute of the resource
     */
    public /*out*/ readonly windSpeeds!: pulumi.Output<outputs.SegmentWindSpeed[]>;

    /**
     * Create a Segment resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: SegmentArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: SegmentArgs | SegmentState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as SegmentState | undefined;
            resourceInputs["altitude"] = state ? state.altitude : undefined;
            resourceInputs["azimuth"] = state ? state.azimuth : undefined;
            resourceInputs["cumulativeDistance"] = state ? state.cumulativeDistance : undefined;
            resourceInputs["description"] = state ? state.description : undefined;
            resourceInputs["geometry"] = state ? state.geometry : undefined;
            resourceInputs["kinds"] = state ? state.kinds : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["tags"] = state ? state.tags : undefined;
            resourceInputs["temperatures"] = state ? state.temperatures : undefined;
            resourceInputs["windDirections"] = state ? state.windDirections : undefined;
            resourceInputs["windSpeeds"] = state ? state.windSpeeds : undefined;
        } else {
            const args = argsOrState as SegmentArgs | undefined;
            if ((!args || args.altitude === undefined) && !opts.urn) {
                throw new Error("Missing required property 'altitude'");
            }
            if ((!args || args.azimuth === undefined) && !opts.urn) {
                throw new Error("Missing required property 'azimuth'");
            }
            if ((!args || args.cumulativeDistance === undefined) && !opts.urn) {
                throw new Error("Missing required property 'cumulativeDistance'");
            }
            resourceInputs["altitude"] = args ? args.altitude : undefined;
            resourceInputs["azimuth"] = args ? args.azimuth : undefined;
            resourceInputs["cumulativeDistance"] = args ? args.cumulativeDistance : undefined;
            resourceInputs["description"] = args ? args.description : undefined;
            resourceInputs["geometry"] = args ? args.geometry : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["tags"] = args ? args.tags : undefined;
            resourceInputs["kinds"] = undefined /*out*/;
            resourceInputs["temperatures"] = undefined /*out*/;
            resourceInputs["windDirections"] = undefined /*out*/;
            resourceInputs["windSpeeds"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Segment.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Segment resources.
 */
export interface SegmentState {
    /**
     * attribute of the resource
     */
    altitude?: pulumi.Input<inputs.SegmentAltitude>;
    /**
     * attribute of the resource
     */
    azimuth?: pulumi.Input<inputs.SegmentAzimuth>;
    /**
     * attribute of the resource
     */
    cumulativeDistance?: pulumi.Input<inputs.SegmentCumulativeDistance>;
    /**
     * description of the resource
     */
    description?: pulumi.Input<string>;
    /**
     * geo position and shape of the resource
     */
    geometry?: pulumi.Input<string>;
    /**
     * kind of the resource
     */
    kinds?: pulumi.Input<pulumi.Input<inputs.SegmentKind>[]>;
    /**
     * name of the resource
     */
    name?: pulumi.Input<string>;
    /**
     * tags of the resource
     */
    tags?: pulumi.Input<pulumi.Input<inputs.SegmentTag>[]>;
    /**
     * attribute of the resource
     */
    temperatures?: pulumi.Input<pulumi.Input<inputs.SegmentTemperature>[]>;
    /**
     * attribute of the resource
     */
    windDirections?: pulumi.Input<pulumi.Input<inputs.SegmentWindDirection>[]>;
    /**
     * attribute of the resource
     */
    windSpeeds?: pulumi.Input<pulumi.Input<inputs.SegmentWindSpeed>[]>;
}

/**
 * The set of arguments for constructing a Segment resource.
 */
export interface SegmentArgs {
    /**
     * attribute of the resource
     */
    altitude: pulumi.Input<inputs.SegmentAltitude>;
    /**
     * attribute of the resource
     */
    azimuth: pulumi.Input<inputs.SegmentAzimuth>;
    /**
     * attribute of the resource
     */
    cumulativeDistance: pulumi.Input<inputs.SegmentCumulativeDistance>;
    /**
     * description of the resource
     */
    description?: pulumi.Input<string>;
    /**
     * geo position and shape of the resource
     */
    geometry?: pulumi.Input<string>;
    /**
     * name of the resource
     */
    name?: pulumi.Input<string>;
    /**
     * tags of the resource
     */
    tags?: pulumi.Input<pulumi.Input<inputs.SegmentTag>[]>;
}
